"""Added initial tables

Revision ID: 18ce144b662c
Revises:
Create Date: 2023-07-02 16:07:55.772576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18ce144b662c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("serverkey", sa.String(length=255), nullable=True),
        sa.Column("masterkey", sa.String(length=64), nullable=True),
        sa.Column("nonce", sa.String(length=24), nullable=True),
        sa.Column("tag", sa.String(length=32), nullable=True),
        sa.Column("role", sa.Enum("admin", "user", name="roles"), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("title_key_tag", sa.String(length=24), nullable=True),
        sa.Column("title_key_nonce", sa.String(length=32), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("content_key_tag", sa.String(length=24), nullable=True),
        sa.Column("content_key_nonce", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entries")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
